 version: '3.8'
 services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: db_task
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./task-back
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      #  SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/db_task
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db_task
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
    volumes:
      - faces_volume:/app/data
  frontend:
    build: ./task-front
    ports:
      - "4200:80"
    depends_on:
      - backend
 volumes:
  pgdata:
  faces_volume: